### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by JFronny** [Xwilarg/BooruSharp#2]
It would be useful to provide .Net Core builds in the NuGet package. I use this in an application i want to migrate and this is one of the only packages that do not support .Net Core

**Comment by Xwilarg** [comment]
Hi,

Sorry for that, I'll work on it and let another message when it'll be done.

**Comment by Xwilarg** [comment]
Well was faster to do than I thought, please tell me if it works properly for you.
You can find the NuGet package here: https://www.nuget.org/packages/BooruSharp/1.4.7

**Comment by JFronny** [comment]
Seems to work well! The only thing is that VS doesn't recognize it as NetCore. I think it wants you to copy the DLL over to another folder inside lib (not net45). I found DSharpPlus to place it in "netstandard2.0". That seems to work for their package

**Comment by Xwilarg** [comment]
(On a side note: I'll try to see if I can make VS reconize it as a .Net Core project when I'll have some time)

**Comment by Xwilarg** [comment]
The project is now fully upgraded to .NET Standard
https://www.nuget.org/packages/BooruSharp/1.4.8
