### ISSUE TITLE
Pixiv Bookmarks?

### ISSUE THREAD

**Issue by da3dsoul** [Xwilarg/BooruSharp#31]
I'm trying to port an excessively bad tool I threw together in Python to a legit netcore service, and I'm looking for Pixiv tools to replace PixivUtil2.

The big feature I'm looking for is the ability to get the latest x (pages) of bookmarked images. Is that a possibility?

I looked around in the code, and I saw no mention of it, so I figured I'd ask.

**Comment by Xwilarg** [comment]
Hi,
For now there are only the options to add and remove bookmarks.
I'll have a look if I can implement the ability to get bookmarks easily but I can't promise anything tho

I'll keep you in touch with my progresses

**Comment by da3dsoul** [comment]
I appreciate it. I like that this one implements other options in a generic way. I might take a stab at it if I can get a testing environment up and going.

**Comment by Xwilarg** [comment]
The ability to get bookmark might not be as generic as the others features since I don't think booru websites have an API endpoint for that

**Comment by da3dsoul** [comment]
I honestly don't even know which boorus have bookmark-like features.

**Comment by da3dsoul** [comment]
A flag like many of the others as HasBrowseableBookmarks could be implemented. The only boorus I've used personally are Gelbooru and Konachan

**Comment by Xwilarg** [comment]
> 
> 
> I honestly don't even know which boorus have bookmark-like features.

I think most of them have something like that, if you're asking which ones are implemented in this library, you can use the [big table in the README](https://github.com/Xwilarg/BooruSharp#features-availability) as a reference

> 
> 
> A flag like many of the others as HasBrowseableBookmarks could be implemented. The only boorus I've used personally are Gelbooru and Konachan

Since no booru have a "get bookmark" endpoint (except Pixiv) I'll probably only look into this one for now

**Comment by Xwilarg** [comment]
Well I think I found what was the endpoint to get the bookmarked illustrations ( https://app-api.pixiv.net/v1/user/bookmarks/illust )
I will just need to find a way to clean the unit tests a bit before trying anything, since they are a huge mess right now

**Comment by Xwilarg** [comment]
Hey,

It's been a bit of time but I began to work on Pixiv bookmark and I wanted to know if it was okay for you before merging it with the main branch
It works like that:
```Cs
var booru = new Pixiv();
await booru.LoginAsync(refresh_token);
var result = await booru.GetFavoritesAsync(profile_id);
```

**Comment by da3dsoul** [comment]
Ah neat. Thanks much!

**Comment by Xwilarg** [comment]
The feature is now available on [BooruSharp.Others 2.2.0](https://www.nuget.org/packages/BooruSharp.Others/2.2.0)
(You may need to wait a bit for the page to work)

Feel free to tell me if you need some additional features or if you encounter an issue with this one

**Comment by da3dsoul** [comment]
Will do. Thanks
