### ISSUE TITLE
Pixiv authentification no longer works

### ISSUE THREAD

**Issue by Xwilarg** [Xwilarg/BooruSharp#32]
Pixiv authentification seems to have change something because all authentification attempt using BooruSharp.Other now returns an error

I'm opening this issue if someone want to help looking into that

This is related to #31

**Comment by n-ski** [comment]
According to this thread https://github.com/upbit/pixivpy/issues/158 username/password auth is no longer supported, it seems the only way to authorize now is to use refresh token.

**Comment by Xwilarg** [comment]
Ah, thanks a lot, I'll look into that

**Comment by Xwilarg** [comment]
Issue solved with BooruSharp.Others 2.1.0
