### ISSUE TITLE
Booru ratings have changed, things are broken

### ISSUE THREAD

**Issue by Keelhauled** [Xwilarg/BooruSharp#39]
https://danbooru.donmai.us/wiki_pages/howto%3Arate

ABooru.GetRating throws if the new rating is found and "safe" rating was renamed to "sensitive" which might break more stuff if adjusted.

**Comment by Xwilarg** [comment]
Hey, thanks for the issue and the pr, I'll check everything once I'll be home
I checked your link and you mean that safe was replaced by general and sensitive was added, right?

**Comment by Keelhauled** [comment]
To me it seems like general is new and safe was renamed, since safe is more similar to sensitive. But it doesn't really matter.

**Comment by Xwilarg** [comment]
You are right, you might want to not rename "Safe" in the PR tho since it'll break the code of people updating their code to this new version (and since it might be specific to Danbooru?)

**Comment by Keelhauled** [comment]
It's also changed on gelbooru but yeah i can change it back

**Comment by Xwilarg** [comment]
I think it would be nice to reflect on the comment (or smth else) that general is not implemented for all booru (and when it's not the case, safe is the "safest" one), that would avoid people thinking it's a bug

**Comment by Keelhauled** [comment]
Is it really important though, if the booru doesn't support general it will simply not appear ever. Unless there is something i don't know about the api. I'll add the comment though.

**Comment by Xwilarg** [comment]
Yeah, what I meant is that people shouldn't except to listen to General for all booru is they want something totally safe because it might not be implemented

**Comment by Keelhauled** [comment]
So everything good? Can you push a nuget update?

**Comment by Xwilarg** [comment]
Yeah sorry was a bit busy, I'll do that today

**Comment by Xwilarg** [comment]
Package is being published
https://www.nuget.org/packages/BooruSharp/3.2.0

It might need a few hours to be validated/indexed

**Comment by Keelhauled** [comment]
Thank you
