### ISSUE TITLE
E621 authorization

### ISSUE THREAD

**Issue by KoB-Kirito** [Xwilarg/BooruSharp#44]
E621 seems not to authorize. I tried with (user_name, api_key) and (user_id, api_key).
But for example `cub -rating:safe`, which need authorization to show anything still results in empty results.

**Comment by Xwilarg** [comment]
You need to create a new instance of BooruAuth with your user id and password hash
https://github.com/Xwilarg/BooruSharp/blob/e3b9e72d6210dd083e9a69c4628f55f5abfb47b4/BooruSharp/Booru/BooruAuth.cs#L16

More information on that here: https://github.com/Xwilarg/BooruSharp#booru

**Comment by KoB-Kirito** [comment]
I do, but e621 does not have a password hash. You used to need the api key, but it does nothing.

**Comment by Xwilarg** [comment]
Uhm, I'll need to investigate that

**Comment by Xwilarg** [comment]
Should be fixed with version 3.4.0: https://www.nuget.org/packages/BooruSharp/3.4.0
