### ISSUE TITLE
Add support for philomena image boards

### ISSUE THREAD

**Issue by KoB-Kirito** [Xwilarg/BooruSharp#45]
Have you considered adding support for [Philomena](https://github.com/ZizzyDizzyMC/philomena)?
[derpibooru.org](https://derpibooru.org/) and [ponybooru.org](https://ponybooru.org/) use that for example.

**Comment by Xwilarg** [comment]
I didn't know about them, do they have an API?

**Comment by KoB-Kirito** [comment]
Yup.
https://www.derpibooru.org/pages/api

**Comment by Xwilarg** [comment]
Ah great, that sounds like a good idea then, I however will be busy until the 7th so I'll begin to have a look at that time

**Comment by KoB-Kirito** [comment]
Found one more that uses almost the same api: https://twibooru.org/
